callable predicates for `filter_by` and `group_by`
gumyr/build123d pull request #177
Opened 2023-03-14 17:01 UTC by snoyer

Proposal to add callable predicates to `ShapeList`'s `filter_by` and `group_by`.

- `filter_by` accepts an arbitrary `Callable[[Shape], bool]` type in additon  to `Axis` and `GeomType`.
- `group_by` accepts an arbitrary `Callable[[Shape], K]` (where `K` is the grouping key) type in addition to `Axis` and `SortBy`.
- additionally `group_by` returns a `GroupBy` object instead of a `list`. this object is still subscriptable by index, but also allows to retrieve the groups by key or by shape.
- internally the old argument types are converted to callable, this should simplify the code and facilitate future additions.

The PR is not merge-ready (I haven't updated the docstrings and there may be a few typing tweaks to do) but here it is for discussion.

2023-03-14 17:12 UTC, snoyer commented
Interestingly a [single test failed](https://github.com/gumyr/build123d/actions/runs/4418290801/jobs/7745209470#step:4:81) on only one of the 6 runners. @gumyr is that a thing known to happen, or do you think I broke the code in an non-obvious way?

2023-03-14 17:29 UTC, gumyr commented
I've seen a single test fail like that a few times.  I'm used to this in very large real-time systems which are difficult to make fully deterministic but to see it here is a little worrisome. I haven't really spent any time investigating but at first glance I didn't see a pattern.

2023-03-15 02:44 UTC, snoyer commented
> to see it here is a little worrisome. I haven't really spent any time investigating but at first glance I didn't see a pattern.

A few commits later the single seemingly unrelated test (`test_regular_polygon_matches_polar`) that failed the first time only on `3.10, windows` is now passing. Should we blame cosmic rays at the github datacenter and move on? (unless more intermittent failures pop up in the future)

2023-03-26 14:09 UTC, gumyr requested changes
This is fancy stuff - thanks. It looks like others on the discord have similar ideas so although I hadn't thought to use the filters this way there is certainly value.  As you say, a few docstrings are missing but otherwise it looks good.

2023-03-26 14:09 UTC, gumyr commented on tests/test_direct_api.py
> +        boxesA = [Solid.make_box(1, 1, 1) for _ in range(3)]
`[Solid.make_box(1, 1, 1)] * 3` ?

2023-04-12 14:59 UTC, snoyer commented on tests/test_direct_api.py
> +        boxesA = [Solid.make_box(1, 1, 1) for _ in range(3)]
That would put the same instance 3 times in the list which wasn't the intent. However in this one test it looks like it would work either way. Let me know.

2023-04-18 14:50 UTC, merged

2023-04-18 14:51 UTC, gumyr commented
Thank you