New section "Iterating Over Compounds" to Assembly documentation.
gumyr/build123d pull request #713
Opened 2024-09-25 00:26 UTC by slobberingant

Iterating over compounds like this has been a solution to a few of my previous problems and I haven't seen it in the documentation. Hope it helps.

2024-09-25 13:27 UTC, gumyr requested changes
One minor change if you don't mind.  The `sum` doesn't need the list comprehension, if its implemented as `sum(part.volume for part in assembly3.solids())` it is called a **generator expression** and is the recommended way to do sums like this.

2024-09-25 14:24 UTC, jdegenstein commented on docs/assemblies.rst
> +As Compounds are containers for shapes, Build123 can iterate over these as required.
please use "build123d" -- all lowercase as per convention in Python

2024-09-26 03:55 UTC, slobberingant commented
Feedback has been incorporated. Thank you.

2024-09-26 14:45 UTC, merged

2024-09-26 14:45 UTC, gumyr commented
Thanks!