Align
gumyr/build123d pull request #782
Opened 2024-11-13 00:12 UTC by erooke

While using `build123d` I noticed that the type signature for `BoundBox.to_align_offset` was wrong. While fixing it I noticed that there was a lot of replicated aligning logic. This is an attempt to rectify that.

- add a generic `to_align_offset` function to the `geometry` module to allow for aligning
- add an `Align.NONE` enum member
- change `to_align_offset` to return a `Vector` as every call site immediately constructed a vector anyway
- change aligning logic for `RegularPolygon` to align based on bounding box (!!)

Not sure if there is interest in merging such a pr. If so I can go ahead and make sure the documentation lines up with the changes and make any changes y'all deem appropriate.

Would close:
- #781 
- #457

Supersedes:
- #734

2024-11-13 20:11 UTC, gumyr requested changes
There should be some tests of `Align.NONE` (even though they might not increase coverage).

2024-11-13 20:11 UTC, gumyr commented on src/build123d/geometry.py
> +    min_point: Sequence[float],
I think this function would make more sense if the inputs were `VectorLike` then all of the math could be done with Vectors instead of looping over floats.

2024-11-13 20:11 UTC, gumyr commented on src/build123d/build_enums.py
> +    NONE = None
I'd like to introduce the following two TypeVars here that can be used on all of the objects (not necessarily in the PR):
```py
Align2DType = TypeVar(
    "Align2DType", Union[Align, None], Tuple[Union[Align, None], Union[Align, None]]
)
Align3DType = TypeVar(
    "Align3DType",
    Union[Align, None],
    Tuple[Union[Align, None], Union[Align, None], Union[Align, None]],
)
```
This could be done later though.

2024-11-13 20:11 UTC, gumyr commented on src/build123d/geometry.py
> +    align: Sequence[Align],
align could also be None so I think should be typed as `align: Sequence[Union[Align,None]]`.

2024-11-14 03:12 UTC, erooke commented on src/build123d/build_enums.py
> +    NONE = None
I was under the impression that typevars were meant to signal [generics](https://docs.python.org/3/library/typing.html#generics). I have added these using [type aliases](https://docs.python.org/3/library/typing.html#type-aliases) as that feels more correct to me.

2024-11-14 03:14 UTC, erooke commented on src/build123d/geometry.py
> +    min_point: Sequence[float],
I'm not sure I follow how making them vectors helps us avoid the looping behavior in the general case. I have changed to `VectorLike` as the signature and the only place I could see to remove the looping behavior was in the trivial case where we have a single alignment variable.

2024-11-14 03:16 UTC, erooke commented on src/build123d/geometry.py
> +    align: Sequence[Align],
That makes sense to me. I guess if we add the `Align2DType` and `Align3DType` it could be typed `Union[Align2DType, Align3DType]`

2024-11-14 03:19 UTC, erooke commented
Made the requested changes, waiting to make sure the design aspects are ironed out before adding tests.

2024-11-14 14:58 UTC, gumyr commented on src/build123d/build_enums.py
> +    NONE = None
"The [type](https://docs.python.org/3/reference/simple_stmts.html#type) statement is new in Python 3.12." but build123d support 3.9-3.12. It doesn't appear to available in `typing_extensions` either.

2024-11-14 15:14 UTC, erooke commented on src/build123d/build_enums.py
> +    NONE = None
From further down the page:
> For backwards compatibility, type aliases can also be created through simple assignment:
> ```
> Vector = list[float]
> ```
> Or marked with [TypeAlias](https://docs.python.org/3/library/typing.html#typing.TypeAlias) to make it explicit that this is a type alias, not a normal variable assignment

`TypeAlias` is in `typing_extensions` and so is what I used here. It passes the CI test suite on 3.9.

2024-11-14 15:21 UTC, gumyr commented on src/build123d/build_enums.py
> +    NONE = None
I'm learning about `TypeAlias` :)

2024-11-14 15:23 UTC, gumyr commented
> Made the requested changes, waiting to make sure the design aspects are ironed out before adding tests.

I'm surprised there is no coverage for the existing Align tests - I would have guessed that there are tests that would have covered them already. Add a few tests for the Align options shouldn't be difficult though.

2024-11-17 13:47 UTC, erooke commented
Added some, potentially overkill, tests. Wasn't quite sure where to stick them so I just threw them in their own file for now.

2024-11-17 14:58 UTC, gumyr commented
This looks good to me.  Are you ready to merge?

2024-11-17 16:19 UTC, erooke commented
> This looks good to me. Are you ready to merge?

Yup, forgot it was still a draft.

2024-11-18 14:33 UTC, merged

2024-11-18 14:34 UTC, gumyr commented
Thank you!